### PR TITLE
Adding support for directions with traffic

### PR DESCRIPTION
**Pull request by fr33fr0m**
Noticed current version is missing the duration in traffic field for direction legs, added the field to Leg class and included a unit test that verifies values are coming back when calling Google's API.

### CODE REVIEW

**Comment by maximn** [comment]
Can you please verify `StartLocation` in the test ?

**Comment by fr33fr0m** [comment]
Hey @maximn, not sure I follow. What's the point of testing StartLocation in a test that's dealing with directions with traffic?

I though you might be looking to assert the request's origin being the same as response's start location but I noticed StartLocation contains only coordinates, if I inspect the first leg while running that test this is what I'm seeing:
```
result.Routes.First().Legs.First().StartLocation
    Latitude: 40.7141218
    LocationString: "40.7141218,-73.9615372"
    Longitude: -73.9615372
```
I guess I could test for StartLocation not being null for all legs but it would be confusing seeing this test fail if Goggle decides to stop populating that field for Directions queries in the future.

**Comment by maximn** [comment]
Sorry, it looked like it was changed from the diff.

**Comment by maximn** [comment]
Nuget v0.63

**Comment by maximn** [comment]
Nuget v0.63

**Pull request merged**
