### PR TITLE
Added support for Encoded polyline based Static map and API Key

### PR DESCRIPTION
**Pull request by nilesh-shah**
- Added support for encoded polyline to render static map url
- Added support for passing API Key to static map
- Updated the Test under MapsApiTest Project (Did not show how to pass API Key in the test but it should be same as DirectionsRequest)

### CODE REVIEW

**Comment by maximn** [comment]
Hi, please try to separate different functionality to separate pull requests (api key - polyline)

I would prefer that the library user won't have to deal with the encoded lines.
What about making the static map to be able to use `OverviewPolyline` ?

**Comment by nilesh-shah** [comment]
Hello @maximn 
Thank you for the review comments.
Yes, in theory we can use `OverviewPolyline`. However, I have noticed that, for considerably large distances, the list of points is large and it generates a pretty long `HTTP GET` request to the static map. There are chances that it goes beyond the Google restriction of # No of characters in the static map request. Please also note that, I have made the property access public, only for GET purpose and library users will not be able to set it from outside. As the static map allows the request to be made using encoded polyline, this library should support that and hence I thought to add it.

I agree with your comment on merging 2 separate functionality in a single check-in and I can revise the same. Please let me know if I generate 2 Pull requests, would you be able to merge them?

Thanks
Nilesh

**Comment by maximn** [comment]
Hi,

If you do separate PRs we can merge what we agree on and discuss what we don't agree.

I agree that this will be  nice to add this functionality, what I'm saying is that we shouldn't expose the encoded points string to the user of the lib. The static map should be able to get the `OverviewPolyline` and use it to generate the StaticMap req.

**Comment by nilesh-shah** [comment]
Closing the PR, as i will create new ones.

**Pull request closed without merging**
