### PR TITLE
add Components to GeocodingRequest

### PR DESCRIPTION
**Pull request by kstensberg**
added a components filter to GeocodingRequest.  see https://developers.google.com/maps/documentation/geocoding/intro#ComponentFiltering

### CODE REVIEW

**Comment by lucasfogliarini** [comment]
I think with this implementation the required fields should not be more "Location OR Address", we can change to "Location, Address or Components". A sample query with components only: https://maps.googleapis.com/maps/api/geocode/json?components=postal_code:90250020.
Coincidentally I did a very similar implementation with your in another project, almost the same time that you opened this PR, and i will present in another PR. Fine?

**Comment by maximn** [comment]
Sounds good. @kstensberg : what do you think?

**Comment by maximn** [comment]
https://github.com/maximn/google-maps/issues/60

**Comment by lucasfogliarini** [comment]
Done.
#67

**Comment by kstensberg** [comment]
@lucasfogliarini, @maximn  I think that makes total sense

**Pull request closed without merging**
