### PR TITLE
Upgraded to .Net Core style project and added package build targets

### PR DESCRIPTION
**Pull request by gguillen**
Upgraded to .Net Core style project. Now supports .net 5, .net 6, .net standard 2.0, net framework 4.6.1.

### CODE REVIEW

**Comment by gguillen** [comment]
I only have a geocode key so I was not able to test the other API endpoints.  If someone could confirm they work, should be good to go.  I updated the ci file, but I am not familiar with it and it might not be right, but the tests pass in VS.

**Comment by maximn** [comment]
I think that you can get a free api key here - https://console.cloud.google.com/google/maps-apis/overview
I'll have a look soon in a week +/-

**Comment by maximn** [comment]
@gguillen Hi, note that you've added your API key to the code of the project ... I would suggest to revoke it.

**Comment by gguillen** [comment]
Yea, I saw that right when I committed it so I rotated it.  Thanks.

**Pull request merged**
