### PR TITLE
Added ability to add referrer to request

### PR DESCRIPTION
**Pull request by jpspringall**
Added the ability to send the referrer with the request, so that google authorisation works.

As i don't have access the google developer console, I've not been able to add unit tests as it will need it's own api key and referrer set

### CODE REVIEW

**Comment by maximn** [comment]
A lot of idents and formatting in the same commit which makes it much harder to review :(

**Comment by maximn** [comment]
If you don't have access to google dev console - why do you need this feature for?
I'm really trying to understand the need here.
It feels a bit strange to use HTTP Reffer for validating a key when doing server to server call. 
Also, not sure if it should be set at the request level or HttpClient level.

**Comment by jpspringall** [comment]
Hi Maxim,

Sorry for the confusion, I thought you had baked an API key into the unit test.

So yes I can do tests with my own API key.

The reason I need this is because our site currently has a dynamic ip address, so therefore I can't do IP authorisation, so I was using the referrer key as a way of implementing authorisation.

However it now appears likely that we can get static IPs, so this change be required.

I'll close the pull request if this is the case.

**Comment by maximn** [comment]
Just before you close. It seems to me like adding a refferer doesn't really makes the authorization stronger in server to server call.

I think this meant to use for API calls going from the browser, in this case it'll be limited only to your website. 

Sorry for discussing it a bit late after you issued a pull request.

**Comment by jpspringall** [comment]
Hi Maxim,

Because in code you can set the referrer to whatever you like in code, if you think of API Key as the username, I was essentially going to be using the referrer value as my password, for example:

GoogleMapsApi.GoogleMaps.PlaceAutocomplete.Query(autoCompleteRequest, "password.local");

And the reason I went for putting it at httpclient level, was because you add the referrer to the httpclient, similar to the timeout whereas the request was essentially the query string.

Anyway I'm still awaiting confirmation, about static ips, at which point I'll close the pull request

**Comment by maximn** [comment]
I think you can use the ApiKey as username & password, you don't need both. I don't think it adds any layer of security.

**Pull request closed without merging**
