### PR TITLE
Feature/additional vehicle type

### PR DESCRIPTION
**Pull request by oliverchristen**
Resolves the following issue: #118 
I also updated NewtonsoftJson and NUnit.

### CODE REVIEW

**Comment by oliverchristen** [comment]
CI build fails because google do not allow too many automated request on their API.

**Comment by oliverchristen** [comment]
I had to ignore those failing tests.

**Comment by maximn** [comment]
I'll merge this. In the future please split to separate PRs. (nunit, newtonsoft, vehicle type)

**Comment by maximn** [comment]
Nuget v0.74.0

**Comment by oliverchristen** [comment]
Hi Maxim

Thank you for immediate action. I very appreciate it!

Best regards,
Oliver

Von: Maxim Novak
Gesendet: Mittwoch, 29. August, 19:10
Betreff: Re: [maximn/google-maps] Feature/additional vehicle type (#119)
An: maximn/google-maps
Cc: Oliver Christen, State change


Nuget v0.74.0

**Pull request merged**
