### PR TITLE
Support targeting .NET Standard 

### PR DESCRIPTION
**Pull request by bergbria**
Maintains support for .net 4.5 builds, adds .net standard 2.0 support

### CODE REVIEW

**Comment by bergbria** [comment]
@maximn / others - I've converted the main library to .net standard and the tests to .net core 3.0. This all builds successfully but I don't really know how to update the github CI configuration. Any pointers?

**Comment by maximn** [comment]
https://github.com/maximn/google-maps/blob/master/.travis.yml

**Comment by maximn** [comment]
I think that we need to fix the tests on master first before changing.
It's a bit flaky and from time to time breaks becuase it's an integration with goole maps server. Can you have a look at that?

**Comment by derigel23** [comment]
@maximn any foreseeable plans to migrate library to .NET Core?

**Comment by maximn** [comment]
@derigel23 
Hi, I don't have Windows and not using .NET anymore. 
Do you think that I can run .net core on my Mac?
Otherwise, if you're willing to contribute and fix I'll merge it.

**Comment by derigel23** [comment]
Yes, you definitely can run .NET Core on Mac.
And use free VS Code or trial JetBrains Rider as an IDE.
I'll try to look at and fix tests (as I understand it's a main blocker for merging this PR).

**Comment by maximn** [comment]
I'm not available for this right now. I'll try to have a look on it in a few months.
If you have the time you're welcome to contribute and I'll merge it. Thanks!

**Comment by gguillen** [comment]
I just submitted [https://github.com/maximn/google-maps/pull/144](https://github.com/maximn/google-maps/pull/144).  It would be nice if I could get some more eyes on apis other than the geocoding ones.

**Pull request closed without merging**
