### PR TITLE
netstandard 2.0 support

### PR DESCRIPTION
**Pull request by rukeba**
Hello team,

I have been using this great library in an legacy project.
Now the project is in the process of migrating to NET 5/6 and the .netstandard packages help a lot.
It would be great if GoogleMaps had a .netstandard build too.

### CODE REVIEW

**Comment by rukeba** [comment]
@maximn thanks.

What about new version in NuGet?

**Comment by maximn** [comment]
The action to publish failed.
https://github.com/maximn/google-maps/actions/runs/3002428542

I'll try to find some time to look at it. If you can check it as well please go ahead.

**Comment by maximn** [comment]
Actually I see that it was published, please verify this - https://www.nuget.org/packages/GoogleMapsApi/1.2.1

**Comment by rukeba** [comment]
Verified. netstandard2.0 build works.
Thank you very much.

**Pull request merged**
