### PR TITLE
Fixed UNIX timestamp daylight savings time issue

### PR DESCRIPTION
**Pull request by mklimmasch**

### CODE REVIEW

**Comment by maximn** [comment]
I think something went wrong with your pull request. Instead of adding it to the open pull request the old one was closed and we have this new one without the previous changes. Please resolve the issue. Let me know if you need help with that.

**Comment by mklimmasch** [comment]
Yeah, I kind of messed up my repo so I decided it was quicker to just redo the original change. The CI build ran into a timeout though. Going to retrigger a build now.

**Comment by maximn** [comment]
Good, but now we're missing the test.

**Comment by mklimmasch** [comment]
Tests are there now. Could you check if they are fine with you?

**Comment by maximn** [comment]
Nuget 0.52

**Pull request merged**
