### PR TITLE
support of "Google Maps Distance Matrix API" has been added

### PR DESCRIPTION
**Pull request by vanko-dev**
support of "Google Maps Distance Matrix API" has been added

https://developers.google.com/maps/documentation/distance-matrix/

### CODE REVIEW

**Comment by vanko-dev** [comment]
also
Two events for interception purposes have been added:
OnUriCreated
OnRawResponseRecivied

**Comment by maximn** [comment]
Hi, in future better to do such pull request as 2 separate pull requests.
1st commit looks good.
2nd have a small comment, wrote on the code.

**Comment by maximn** [comment]
I believe your second commit will solve
https://github.com/maximn/google-maps/issues/45

**Comment by vanko-dev** [comment]
HI, 

> What do you think about making the signature
> Uri UriCreatedDelegate(Uri uri);
> ?
> So instead of the ref you just return the new uri.
> Feels cleaner to do return otherUri than uri = otherUri

It's not important for me. I use it for logging purposes and not change Uri, but I think it may be helpful in some cases

**Comment by maximn** [comment]
@vanko-dev 
As I mentioned in a different comment, changing the URL will solve https://github.com/maximn/google-maps/issues/45
Please change it to the nicer signature. Then I'll merge.

**Comment by vanko-dev** [comment]
@maximn 

> As I mentioned in a different comment, changing the URL will solve #45 

this is a  test for it: 
DistanceMatrixTests.ShouldReplaceUriViaOnUriCreated

**Comment by maximn** [comment]
@vanko-dev very strange, the build for PR was green, but after merging test are failing.
I don't have windows anymore and hard to check it , do you have an idea?

1) Test Failure : GoogleMapsApi.Test.IntegrationTests.DistanceMatrixTests.ShouldPassRawDataToOnRawResponseRecivied
     Expected: OK
  But was:  REQUEST_DENIED
at GoogleMapsApi.Test.IntegrationTests.DistanceMatrixTests.ShouldPassRawDataToOnRawResponseRecivied () <0x40abe020 + 0x003b1> in <filename unknown>:0
2) Test Failure : GoogleMapsApi.Test.IntegrationTests.DistanceMatrixTests.ShouldReplaceUriViaOnUriCreated
     Expected: OK
  But was:  REQUEST_DENIED
at GoogleMapsApi.Test.IntegrationTests.DistanceMatrixTests.ShouldReplaceUriViaOnUriCreated () <0x40ac2a90 + 0x00305> in <filename unknown>:0
3) Test Failure : GoogleMapsApi.Test.IntegrationTests.DistanceMatrixTests.ShouldReturnDurationInTrafficWhenDepartureTimeAndApiKeySpecified
     Expected: OK
  But was:  REQUEST_DENIED
at GoogleMapsApi.Test.IntegrationTests.DistanceMatrixTests.ShouldReturnDurationInTrafficWhenDepartureTimeAndApiKeySpecified () <0x40ac4fa0 + 0x002c8> in <filename unknown>:0

**Comment by vanko-dev** [comment]
hi @maximn,
looks like need to activate Matrix API in Google Developer Console for the your test API key.

**Comment by maximn** [comment]
Correct. Thanks, fixed.

*-- Maxim.*

**Pull request merged**
